rt-sphere-demo:
	g++ rt-sphere.cpp -o rt
	./rt >> demo.ppm

rt-demo:
	g++ rt.cpp -o rt
	./rt >> demo.ppm

vec3-ppm-demo:
	g++ vec3ppm.cpp -o ppm
	./ppm >> demo.ppm

ppm-demo:
	g++ ppm.cpp -o ppm
	./ppm >> demo.ppm

clean:
	rm -f *.o hello.ppm demo.ppm ppm rt
